apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-assistant-deployment
  namespace: ai-assistant-app
  labels:
    app: ai-assistant
spec:
  replicas: 2

  selector:
    matchLabels:
      app: ai-assistant

  template:
    metadata:
      labels:
        app: ai-assistant

    spec:
      containers:
        - name: ai-assistant-container

          image: ai-assistant:v1.0
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: ai-assistant-config
                
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "1"
              memory: "1Gi"

      
